/**
 * API paths — storefront, admin, and tooling.
 * Admin routes require `is_admin` on the user (backend `requireAdmin`).
 */

export const endpoints = {
  auth: {
    signup: '/api/auth/signup',
    login: '/api/auth/login',
    refresh: '/api/auth/refresh',
    logout: '/api/auth/logout',
    me: '/api/auth/me',
    mePatch: '/api/auth/me',
  },
  products: {
    list: '/products',
    sales: '/products/sales',
    facets: '/products/facets',
    search: '/products/search',
    searchImage: '/products/search/image',
    byId: (id: number | string) => `/products/${id}`,
    recommendations: (id: number | string) => `/products/${id}/recommendations`,
    completeStyle: (id: number | string) => `/products/${id}/complete-style`,
    styleProfile: (id: number | string) => `/products/${id}/style-profile`,
    priceHistory: (id: number | string) => `/products/${id}/price-history`,
    similar: (id: number | string) => `/products/${id}/similar`,
    priceDrops: '/products/price-drops',
    images: (id: number | string) => `/products/${id}/images`,
    imagePrimary: (id: number | string, imageId: number | string) =>
      `/products/${id}/images/${imageId}/primary`,
    imageDelete: (id: number | string, imageId: number | string) => `/products/${id}/images/${imageId}`,
    recommendationsBatch: '/products/recommendations/batch',
    completeStylePost: '/products/complete-style',
    completeStyleTryOn: '/products/complete-style/try-on',
    variantsBatch: '/products/variants/batch',
  },
  search: {
    text: '/search',
    image: '/search/image',
    multiImage: '/search/multi-image',
    multiVector: '/search/multi-vector',
    autocomplete: '/search/autocomplete',
    trending: '/search/trending',
    popular: '/search/popular',
    session: (sessionId: string) => `/search/session/${sessionId}`,
    promptTemplates: '/search/prompt-templates',
    promptAnalyze: '/search/prompt-analyze',
    promptSuggestions: '/search/prompt-suggestions',
  },
  images: {
    search: '/api/images/search',
    searchSelective: '/api/images/search/selective',
    searchUrl: '/api/images/search/url',
    analyze: '/api/images/analyze',
    detect: '/api/images/detect',
    detectUrl: '/api/images/detect/url',
    detectBatch: '/api/images/detect/batch',
    labels: '/api/images/labels',
    status: '/api/images/status',
  },
  ingest: {
    image: '/api/ingest/image',
    job: (jobId: string) => `/api/ingest/${jobId}`,
  },
  labeling: {
    tasks: '/api/labeling/tasks',
    taskAssign: (id: string) => `/api/labeling/tasks/${id}/assign`,
    taskSubmit: (id: string) => `/api/labeling/tasks/${id}/submit`,
    taskSkip: (id: string) => `/api/labeling/tasks/${id}/skip`,
    stats: '/api/labeling/stats',
    queue: '/api/labeling/queue',
    categories: '/api/labeling/categories',
    patterns: '/api/labeling/patterns',
    materials: '/api/labeling/materials',
  },
  favorites: {
    list: '/api/favorites',
    toggle: '/api/favorites/toggle',
    check: (productId: number | string) => `/api/favorites/check/${productId}`,
    checkBatch: '/api/favorites/check',
  },
  cart: {
    root: '/api/cart',
    item: (productId: number | string) => `/api/cart/${productId}`,
    clear: '/api/cart/clear',
  },
  wardrobe: {
    items: '/api/wardrobe/items',
    item: (id: number | string) => `/api/wardrobe/items/${id}`,
    profile: '/api/wardrobe/profile',
    profileRecompute: '/api/wardrobe/profile/recompute',
    gaps: '/api/wardrobe/gaps',
    recommendations: '/api/wardrobe/recommendations',
    compatibilityScore: '/api/wardrobe/compatibility/score',
    compatibilityItem: (itemId: string) => `/api/wardrobe/compatibility/${itemId}`,
    compatibilityPrecompute: '/api/wardrobe/compatibility/precompute',
    outfitSuggestions: '/api/wardrobe/outfit-suggestions',
    completeLook: '/api/wardrobe/complete-look',
    backfillEmbeddings: '/api/wardrobe/backfill-embeddings',
    similar: (itemId: string) => `/api/wardrobe/similar/${itemId}`,
    autoSyncSettings: '/api/wardrobe/auto-sync/settings',
    autoSyncManual: '/api/wardrobe/auto-sync/manual',
    analyzePhoto: '/api/wardrobe/analyze-photo',
    analyzePhotosBatch: '/api/wardrobe/analyze-photos/batch',
    itemReanalyze: (id: string) => `/api/wardrobe/items/${id}/re-analyze`,
    outfitCoherence: '/api/wardrobe/outfit-coherence',
    outfitCoherenceById: (outfitId: string) => `/api/wardrobe/outfit/${outfitId}/coherence`,
    layeringAnalyze: '/api/wardrobe/layering/analyze',
    layeringSuggest: '/api/wardrobe/layering/suggest',
    layeringWeather: '/api/wardrobe/layering/weather-check',
    compatibilityCategoryLearned: (category: string) =>
      `/api/wardrobe/compatibility/${encodeURIComponent(category)}/learned`,
    compatibilityGraph: '/api/wardrobe/compatibility/graph',
    compatibilityLearn: '/api/wardrobe/compatibility/learn',
    onboarding: '/api/wardrobe/onboarding',
    essentials: '/api/wardrobe/essentials',
    priceTier: '/api/wardrobe/price-tier',
  },
  tryon: {
    serviceHealth: '/api/tryon/service/health',
    submit: '/api/tryon/',
    fromWardrobe: '/api/tryon/from-wardrobe',
    fromProduct: '/api/tryon/from-product',
    batch: '/api/tryon/batch',
    history: '/api/tryon/history',
    saved: '/api/tryon/saved',
    savedItem: (savedId: string) => `/api/tryon/saved/${savedId}`,
    job: (id: string) => `/api/tryon/${id}`,
    cancel: (id: string) => `/api/tryon/${id}/cancel`,
    save: (id: string) => `/api/tryon/${id}/save`,
    delete: (id: string) => `/api/tryon/${id}`,
  },
  compare: {
    root: '/api/compare',
    /** Decision journey — POST body: CompareDecisionRequest (camelCase). */
    decision: '/api/compare',
    quality: (productId: string) => `/api/compare/quality/${productId}`,
    analyzeText: '/api/compare/analyze-text',
    price: (productId: string) => `/api/compare/price/${productId}`,
    baseline: (category: string) => `/api/compare/baseline/${encodeURIComponent(category)}`,
    computeBaselines: '/api/compare/admin/compute-baselines',
    tooltips: '/api/compare/tooltips',
  },
  admin: {
    hideProduct: (id: string) => `/admin/products/${id}/hide`,
    unhideProduct: (id: string) => `/admin/products/${id}/unhide`,
    flagProduct: (id: string) => `/admin/products/${id}/flag`,
    unflagProduct: (id: string) => `/admin/products/${id}/unflag`,
    hideBatch: '/admin/products/hide-batch',
    flagged: '/admin/products/flagged',
    hidden: '/admin/products/hidden',
    duplicates: (id: string) => `/admin/products/${id}/duplicates`,
    canonicals: '/admin/canonicals',
    canonical: (id: string) => `/admin/canonicals/${id}`,
    canonicalMerge: '/admin/canonicals/merge',
    canonicalDetach: (id: string, productId: string) => `/admin/canonicals/${id}/detach/${productId}`,
    jobRun: (type: string) => `/admin/jobs/${encodeURIComponent(type)}/run`,
    jobSchedules: '/admin/jobs/schedules',
    jobMetrics: '/admin/jobs/metrics',
    jobHistory: '/admin/jobs/history',
    stats: '/admin/stats',
    recoLabel: '/admin/reco/label',
    recoLabelPost: '/admin/reco/label',
    recoLabelBatch: '/admin/reco/label/batch',
    recoLabels: '/admin/reco/labels',
    recoStats: '/admin/reco/stats',
  },
  dashboard: {
    summary: '/api/dashboard/summary',
    products: '/api/dashboard/products',
    productSignals: (id: number | string) => `/api/dashboard/products/${id}/signals`,
    alerts: '/api/dashboard/alerts',
    dismissAlert: (id: number | string) => `/api/dashboard/alerts/${id}/dismiss`,
    generateAlerts: '/api/dashboard/alerts/generate',
  },
  health: {
    live: '/health/live',
    ready: '/health/ready',
    detailed: '/health/detailed',
  },
  metrics: '/metrics',
}
